# Markdown linting configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

# Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  tables: false

# Allow inline HTML
MD033:
  allowed_elements:
    - br
    - hr
    - a
    - img
    - details
    - summary
    - sub
    - sup

# First line should not necessarily be a heading
MD041: false

# Allow duplicate headings
MD024:
  siblings_only: true

# Allow trailing punctuation in headings
MD026: false

# Allow bare URLs
MD034: false

# Allow emphasis used instead of heading
MD036: false