# Prettier configuration for YAML and JSON formatting

# Basic formatting
printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: "as-needed"
trailingComma: "es5"
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
endOfLine: "lf"

# Format on save
requirePragma: false
insertPragma: false

# Markdown
proseWrap: "preserve"
embeddedLanguageFormatting: "auto"

# YAML specific
yamlQuotes:
  avoidEscape: true