# Rust formatting configuration
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
# Unstable features commented out for stable rustfmt
# format_code_in_doc_comments = true
# wrap_comments = true
# comment_width = 80
# normalize_comments = true
# format_strings = true
# imports_granularity = "Module"
# group_imports = "StdExternalCrate"
