title: General Discussion - [Topic]
labels: ["general"]
body: |
  **Topic:**
  
  **Discussion Points:**
  
  **Questions for the Community:**
  
  **Additional Context:**
  
  ---
  *Open discussion about Linux hardware compatibility topics*