title: Hardware Showcase - [Hardware Name]
labels: ["hardware-showcase"]
body: |
  **Hardware:** 
  
  **Compatibility Status:** 
  
  **Configuration Details:**
  
  **Why This Hardware Rocks:**
  
  **Tips for Other Users:**
  
  **Screenshots/Photos:**
  
  ---
  *Share your working Linux hardware setups to help the community!*