title: Help Needed - [Brief Description]
labels: ["help-wanted"]
body: |
  **What I'm Trying to Do:**
  
  **My System:**
  - OS: 
  - Kernel: 
  - Hardware: 
  
  **What I've Tried:**
  
  **Error Messages/Output:**
  ```
  [Paste any error messages or command output here]
  ```
  
  **Additional Context:**
  
  ---
  *Community support for Linux hardware compatibility challenges*