name: Test Simple Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test echo
        run: echo "Testing if workflows can run"

      - name: List files
        run: ls -la

