name: Update Search Indices

on:
  push:
    branches: [main]
    paths:
      - 'hardware/**/*.yaml'
      - 'hardware/**/*.yml'
      - 'hardware/**/*.json'
      - 'web/data/**/*.json'
  pull_request:
    branches: [main]
    paths:
      - 'hardware/**/*.yaml'
      - 'hardware/**/*.yml'
      - 'hardware/**/*.json'
  workflow_dispatch:

jobs:
  update-indices:
    runs-on: ubuntu-latest
    name: Rebuild Search Indices and Statistics
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config jq
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "indexer"
        
    - name: Build indexer
      run: |
        cargo build --release --bin lx-hw-indexer
        
    - name: Count hardware reports
      run: |
        TOTAL_REPORTS=$(find hardware -name "*.yaml" \
          -o -name "*.yml" -o -name "*.json" | wc -l)
        echo "Found $TOTAL_REPORTS hardware reports"
        echo "TOTAL_REPORTS=$TOTAL_REPORTS" >> $GITHUB_ENV
        
    - name: Generate search indices
      run: |
        echo "Generating search indices from hardware reports..."
        
        # Create output directory
        mkdir -p web/data/generated
        
        # Run the indexer to generate search indices
        ./target/release/lx-hw-indexer \
          --input-dir hardware \
          --output-dir web/data/generated \
          --format json \
          --include-statistics
          
    - name: Generate API endpoints
      run: |
        echo "Generating API endpoint data..."
        
        # Create API directory structure
        mkdir -p web/api/v1/{search,stats,recommendations}
        mkdir -p web/api/v1/recommendations/by-use-case
        
        # Generate search endpoints
        ./target/release/lx-hw-indexer \
          --input-dir hardware \
          --output-dir web/api/v1/search \
          --format api \
          --endpoints components,vendors,distributions,kernels
          
        # Generate statistics endpoints
        ./target/release/lx-hw-indexer \
          --input-dir hardware \
          --output-dir web/api/v1/stats \
          --format api \
          --endpoints overview,trends,top-hardware
          
    - name: Update web interface data
      run: |
        echo "Updating web interface data files..."
        
        # Merge generated data with existing web data
        if [ -f web/data/generated/hardware-database.json ]; then
          cp web/data/generated/hardware-database.json \
            web/data/hardware-database.json
        fi
        
        if [ -f web/data/generated/search-indices.json ]; then
          cp web/data/generated/search-indices.json \
            web/data/search-indices.json
        fi
        
    - name: Generate usage statistics
      run: |
        echo "Generating usage statistics..."
        
        # Create statistics summary
        cat > web/statistics/build-info.json << EOF
        {
          "generated_at": "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)",
          "total_hardware_reports": $TOTAL_REPORTS,
          "build_number": "$GITHUB_RUN_NUMBER",
          "commit_sha": "$GITHUB_SHA",
          "workflow_status": "completed"
        }
        EOF
        
    - name: Commit updated indices (if on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if [ -n "$(git status --porcelain)" ]; then
          git add web/data/ web/api/ web/statistics/
          git commit -m "Automated update of search indices and statistics
          
          - Updated search indices for $TOTAL_REPORTS hardware reports
          - Regenerated API endpoints with latest data
          - Updated statistics and build information
          - Generated by GitHub Actions build $GITHUB_RUN_NUMBER
          
          Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          
          git push
        else
          echo "No changes to commit"
        fi
        
    - name: Deploy to GitHub Pages (if on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web
        destination_dir: .
        enable_jekyll: false
        
    - name: Create deployment summary
      run: |
        echo "## Search Index Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Total Hardware Reports:** $TOTAL_REPORTS" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Number:** $GITHUB_RUN_NUMBER" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit SHA:** $(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_STEP_SUMMARY
        echo "- **Generated At:** $(date -u)" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "- **Deployment:** ✅ Deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Deployment:** ⏸️ PR preview (not deployed)" >> $GITHUB_STEP_SUMMARY
        fi
